# Generated by Django 2.2 on 2019-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField()),
                ('assigned_to_id', models.IntegerField(blank=True, null=True)),
                ('priority_id', models.IntegerField()),
                ('fixed_version_id', models.IntegerField(blank=True, null=True)),
                ('author_id', models.IntegerField()),
                ('lock_version', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('done_ratio', models.IntegerField()),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('root_id', models.IntegerField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('is_private', models.IntegerField()),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssueStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_closed', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('default_done_ratio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue_statuses',
                'managed': False,
            },
        ),
    ]
